web:
  build: .
  volumes:
   - .:/code
   - ./docker/php.ini:/usr/local/etc/php/conf.d/default.ini
  links:
   - mysql
nginx:
  image: nginx
  links:
   - web
  volumes:
   - .:/code
   - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "80:80"
mysql:
  image: mariadb:5.5
  volumes:
    - database_volume:/var/lib/mysql
    - ./docker/mariadb.d:/etc/mysql/conf.d
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: dev
    MYSQL_USER: user
    MYSQL_PASSWORD: password
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - mysql
  ports:
   - "443:80"
