apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: my-loadbalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https 
    protocol: TCP
    port: 443
    targetPort: 443

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-loadbalancer
  labels:
    app: my-loadbalancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-loadbalancer
  template:
    metadata:
      labels:
        app: my-loadbalancer
    spec:
      containers:
      - name: nginx
        image: nginx:1.17
        ports:
        - name: http
          protocol: TCP
          containerPort: 80
        - name: https 
          protocol: TCP
          containerPort: 443
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: my-loadbalancer-nginx-configuration

---

# I think HaProxy is better suited, and plays more nicely with automatic LetsEncrypt certificates.
kind: ConfigMap
apiVersion: v1
metadata:
  name: my-loadbalancer-nginx-configuration
data:
  default.conf: |-
    server {
      listen 80;
      server_name _;
    
      location / {
        return 404;
      }
    }

  muzieklijstjes.conf: |-
    server {
      listen 80;
      server_name musiclists.nl;
    
      location / {
        # TODO Should use PROXY protocol
        proxy_pass http://muzieklijstjes.default.svc.cluster.local:80; 
      }
    }
  